---
domain_name: "ad.example.com"

# OU where the VM should be created
domain_join_ou: "OU=Build,OU=Servers,OU=Resources,DC=ad,DC=example,DC=com"

# Local admin group to add the domain group to (e.g. "Administrators")
domain_admin_group: "EXAMPLE\\ServerAdmins"
