---
galaxy_info:
  author: your-team
  description: Clone VMs from Proxmox templates via ssh (qm) with cloud-init / cloudbase-init
  license: MIT
  min_ansible_version: 2.12
  platforms:
    - name: Debian
      versions:
        - buster
        - bullseye
  categories:
    - virtualization

dependencies: []
