- name: Show qm list on proxmox node (delegated to node)
  hosts: localhost
  gather_facts: false
  vars_files:
    - "{{ lookup('env','HOME') }}/ansible-secrets/proxmox/proxmox_creds.yml"
  tasks:
    - name: Run qm list on proxmox node (via SSH) and gather output
      ansible.builtin.command: qm list
      delegate_to: pve01.lab.sal9000.tech
      become: true
      become_user: root
      register: qm_list
      changed_when: false

    - name: Print qm list output lines
      ansible.builtin.debug:
        var: qm_list.stdout_lines
