---
- name: Deploy VMs to Proxmox (Linux & Windows)
  hosts: localhost
  gather_facts: false
  vars_files:
    # - vars/proxmox_creds.yml   # store proxmox.api_* variables and tokens here (git-ignore)
    - ~/ansible-secrets/proxmox/proxmox_creds.yml
  roles:
    - role: proxmox_clone
      proxmox: "{{ proxmox }}"
      provision_vms: "{{ vms_to_provision }}"

# or run from the cli with -e "vms_to_provision=@myvms.yml"
