# vm_config:
#   name: win01
#   template_vmid: 9001
#   vmid: 3001
#   hostname: win01.example.local

#   ip: 192.168.100.201/24
#   gateway: 192.168.100.1
#   dns: 1.1.1.1

#   windows_admin_password: "P@ssword01!"
