---
- name: Prepare VM
  include_tasks: includes/prepare.yml

- name: Provision VM
  include_tasks: includes/provision.yml

- name: Resolve networking
  include_tasks: includes/netbox.yml

- name: Configure Cloud-Init
  include_tasks: includes/cloudinit.yml

- name: Boot VM
  include_tasks: includes/boot.yml
